require 'active_support/concern'
require 'hash-keys'

require 'euston-eventstore/commit'
require 'euston-eventstore/constants'
require 'euston-eventstore/errors'
require 'euston-eventstore/event_message'
require 'euston-eventstore/optimistic_event_store'
require 'euston-eventstore/optimistic_event_stream'
require 'euston-eventstore/snapshot'
require 'euston-eventstore/snapshot_stream_pair'
require 'euston-eventstore/dispatcher/asynchronous_dispatcher'
require 'euston-eventstore/dispatcher/null_dispatcher'
require 'euston-eventstore/dispatcher/synchronous_dispatcher'
require 'euston-eventstore/persistence/stream_head'
require 'euston-eventstore/persistence/mongodb/mongo_commit'
require 'euston-eventstore/persistence/mongodb/mongo_commit_id'
require 'euston-eventstore/persistence/mongodb/mongo_config'
require 'euston-eventstore/persistence/mongodb/mongo_event_message'
require 'euston-eventstore/persistence/mongodb/mongo_persistence_engine'
require 'euston-eventstore/persistence/mongodb/mongo_persistence_factory'
require 'euston-eventstore/persistence/mongodb/mongo_snapshot'
require 'euston-eventstore/persistence/mongodb/mongo_stream_head'

Json = JSON if defined?(JSON) && !defined?(Json)
